site_name: Debugging for mbed

docs_dir: Docs

pages:
- ['index.md','Introduction to Debugging']
- ['Debugging/printf.md','Debugging', 'printf()']
- ['Debugging/pyOCD.md','Debugging', 'pyOCD']
- ['Debugging/Keil.md','Debugging', 'Keil uVision']
- ['Debugging/debugging_microbit.md','Debugging', 'Debugging the BBC micro:bit']
- ['Debugging/offline.md','Debugging', 'Offline Development']
