site_name: Debugging for mbed

docs_dir: Docs

pages:
- ['index.md','Debugging mbed OS applications']
- ['Debugging/printf.md','Debugging', 'Debugging with printf() calls']
- ['Debugging/compile_time.md', 'Debugging', 'Compile time errors']
- ['Debugging/lights_of_dead.md', 'Debugging', 'Lights of dead']
- ['Debugging/toolchain.md','Debugging', 'Setting up a local debugging toolchain']
- ['Debugging/debug_builds.md','Debugging', 'Producing debug builds with mbed CLI']
- ['Debugging/Keil.md','Debugging', 'Debugging with uVision 5']
- ['Debugging/Debugging_Eclipse_pyOCD.md','Debugging', 'Debugging with Eclipse']
- ['Debugging/vscode.md','Debugging', 'Debugging with Visual Studio Code']
- ['Debugging/other_ides.md','Debugging', 'Debugging with other IDEs']
- ['Debugging/debugging_microbit.md','Debugging', 'Debugging the BBC micro:bit']
